.github/workflows/release.yml, package.json
This workflow only works for `main` branch, it builds and tests everything before publishing to registry
=> Added basic release workflow

.github/workflows/release.yml
=> Renamed release job

packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json, packages/web3-react/CHANGELOG.md, packages/web3-react/package.json, packages/web3-react/src/constants/connectors.ts, packages/web3-react/src/helpers/providerDetectors.ts, packages/web3-react/src/hooks/useConnectorInfo.ts
Fixes a minor issue with Zerion wallet detection.
=> Zerion Wallet detection

apps/demo-react/components/ConnectDisconnect.tsx, apps/demo-react/components/MainContainer.tsx, apps/demo-react/components/ProviderWeb3WithProps.tsx, apps/demo-react/components/WalletInfo.tsx, apps/demo-react/package.json, apps/demo-react/pages/index.tsx, yarn.lock
Adds to the demo page:
- some debug info for development purposes
- "disconnect" button
=> Demo React Page: add WalletInfo

packages/connect-wallet-modal/CHANGELOG.md, packages/connect-wallet-modal/package.json, packages/connect-wallet-modal/src/components/ConnectButton/styles.tsx, packages/connect-wallet-modal/src/components/WalletsModal/styles.tsx, packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json
This PR improves the look and behavior of the wallet connection modal's scrollbar.
https://user-images.githubusercontent.com/1245209/214043624-8f7525ae-1374-4166-8d3f-16aa0ba79877.mp4
=> Improve the modal's scrollbar

packages/connect-wallet-modal/CHANGELOG.md, packages/connect-wallet-modal/package.json, packages/connect-wallet-modal/src/components/WalletsModal/WalletsModal.tsx, packages/connect-wallet-modal/src/helpers/useLocalStorage.ts, packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json
=> Fix: add checks that `window` is defined

apps/demo-react/components/WalletInfo.tsx, apps/demo-react/pages/index.tsx, apps/demo-react/styles/global.ts, packages/connect-wallet-modal/CHANGELOG.md, packages/connect-wallet-modal/package.json, packages/connect-wallet-modal/src/components/Terms/Terms.tsx, packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json, packages/ui-react/CHANGELOG.md, packages/ui-react/package.json, packages/ui-react/src/components/modal/ModalStyles.tsx
- Update "I have read and accept Terms of Service and Policy Notice" text (UI-554)
- Make global CSS rules for the demo react app to be similar to what we have on stake widget, to reduce the amount of hidden issues related to differences between global CSS on demo app and widget
- Explicitly set expected `box-sizing: content-box;` css rule for the Modal component and its parts
=> Update Terms text and Modal CSS

packages/web3-react/src/hooks/useConnectorInfo.ts, packages/web3-react/test/hooks/useConnectorInfo.test.ts
See code comments for explanation
=> Fix(web3-react): do not detect providerName if isDappBrowser

packages/connect-wallet-modal/CHANGELOG.md, packages/connect-wallet-modal/package.json, packages/core-react/CHANGELOG.md, packages/core-react/package.json, packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json, packages/wallets-list/CHANGELOG.md, packages/wallets-list/package.json, packages/wallets-list/src/ethereum.ts
This PR enables Phantom wallet in the Ethereum wallets list
=> Phantom enable

packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json, packages/reef-knot/src/packages/connectors.ts, yarn.lock
Forgot to add it here: https://github.com/lidofinance/reef-knot/pull/62
=> Add reef-knot/connectors path

.changeset/rich-ads-sip.md, packages/wallets/phantom/src/icons/phantom.svg
Updated the phantom wallet icon to be in line with the new rebrand here:
https://twitter.com/phantom/status/1674513272115175424
=> updated phantom svg icon

.changeset/heavy-apes-complain.md, packages/connect-wallet-modal/src/connectButtons/ConnectInjected.tsx, packages/connect-wallet-modal/src/connectButtons/ConnectWC.tsx, packages/types/src/walletAdapter.ts, packages/wallets/okx/src/index.ts, packages/wallets/phantom/src/index.ts
=> Remove deprecated "icons" field from Wallets Adapter API

.changeset/silver-falcons-love.md, apps/demo-react/package.json, packages/connect-wallet-modal/package.json, packages/core-react/package.json, packages/types/package.json, packages/ui-react/package.json, packages/wallets-helpers/package.json, packages/wallets/ambire/package.json, packages/wallets/bitkeep/package.json, packages/wallets/blockchaincom/package.json, packages/wallets/exodus/package.json, packages/wallets/okx/package.json, packages/wallets/phantom/package.json, packages/wallets/taho/package.json, packages/wallets/walletconnect/package.json, packages/wallets/zengo/package.json, packages/wallets/zerion/package.json, packages/web3-react/package.json, yarn.lock
Updates WalletConnect deps from 2.8.4 to 2.9.0:
https://github.com/wagmi-dev/wagmi/commit/cebbcd37852b505ef58b7bb97e1bc94ac65f4f1f
https://github.com/WalletConnect/walletconnect-monorepo/releases
Closes UI-879
=> Update wagmi to 0.12.19

.changeset/tasty-eggs-marry.md, packages/connect-wallet-modal/src/components/Terms/Terms.tsx, packages/connect-wallet-modal/src/components/WalletsModal/WalletsModal.tsx, packages/connect-wallet-modal/src/components/WalletsModal/styles.tsx, packages/connect-wallet-modal/src/components/WalletsModal/types.ts, packages/core-react/src/context/acceptTermsModal.tsx, packages/core-react/src/context/index.tsx, packages/core-react/src/context/reefKnot.tsx, packages/core-react/src/hooks/useReefKnotContext.ts, packages/core-react/src/index.ts, packages/web3-react/package.json, packages/web3-react/src/context/web3.tsx, packages/web3-react/src/hooks/useAutoConnect.ts
1. Adds an extra modal window with "Terms of Use and Privacy Notice" checkbox before auto connection in case of Ledger Live, Gnosis Safe iframe, various built into wallets dapp browsers.
2. Add an ability to pass via props links to terms and privacy notice.
Resolves UI-630 (additional info is there)
=> Call additional Terms Modal for Ledger Live, Safe, dapp browsers

.github/workflows/check.yml, apps/demo-react/.env, apps/demo-react/.gitignore
Fix:
- Deploy preview envs
- gitignore
=> fix: preview envs

.changeset/mean-paws-fetch.md, packages/connect-wallet-modal/CHANGELOG.md, packages/connect-wallet-modal/package.json, packages/connect-wallet-modal/src/connectButtons/ConnectLedger.tsx, packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json
Fixes, when successfully conecting ledger, also close main modal.
=> [fix] ledger close modal on success

packages/connect-wallet-modal/CHANGELOG.md, packages/connect-wallet-modal/package.json, packages/connect-wallet-modal/src/components/WalletsModal/components/ConnectWalletModal/ConnectWalletModal.tsx, packages/connect-wallet-modal/src/components/WalletsModal/components/ConnectWalletModal/sortWalletsList.ts, packages/connect-wallet-modal/src/connectButtons/ConnectInjected.tsx, packages/core-react/CHANGELOG.md, packages/core-react/package.json, packages/core-react/src/hooks/useAutoConnectCheck.ts, packages/core-react/src/hooks/useConnect.ts, packages/core-react/src/hooks/useDisconnect.ts, packages/core-react/src/hooks/useEagerConnect.ts, packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json, packages/types/CHANGELOG.md, packages/types/package.json, packages/types/src/walletAdapter.ts, packages/wallets-list/CHANGELOG.md, packages/wallets-list/package.json, packages/wallets/safe/CHANGELOG.md, packages/wallets/safe/package.json, packages/wallets/safe/src/index.ts
=> Async Safe wallet detection

.changeset/pretty-radios-enjoy.md, packages/core-react/CHANGELOG.md, packages/core-react/package.json, packages/core-react/src/hooks/useDisconnect.ts, packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json
Fixes the issue when "disconnect" function is unexpectedly undefined
=> Fix: checkIfDisconnectMakesSense

apps/demo-react/components/ProviderSDKWithProps.tsx
Fixing sdk legacy web3 provider instance value
Should fix bugs on ledger-live and missing add token button. May be also the solution for coin98 bug.
=> fix: sdk legacy web3 provider instance value

packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json, packages/ui-react/CHANGELOG.md, packages/ui-react/package.json, packages/ui-react/src/hooks/useLockScroll.ts
Fixing scroll lock when the modal is open
Original fix https://github.com/lidofinance/ui/pull/480/files#diff-58cf1219d153c7adbb38f4ad513af2e156a11d61f31b96525203c5610efae6e6
=> fix: scroll lock condition

packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json, packages/ui-react/CHANGELOG.md, packages/ui-react/package.json, packages/wallets-helpers/CHANGELOG.md, packages/wallets-helpers/package.json
Properly releasing changes from here: https://github.com/lidofinance/reef-knot/pull/155
=> reef-knot v5.3.1

apps/demo-react/ledger_live_example_manifest.json
Added example manifest for testing with ledger live at `apps/demo-react/ledger_live_example_manifest.json`
=> Add LL example manifest

packages/connect-wallet-modal/CHANGELOG.md, packages/connect-wallet-modal/package.json, packages/connect-wallet-modal/src/components/WalletsModal/WalletsModalForEth.tsx, packages/core-react/CHANGELOG.md, packages/core-react/package.json, packages/core-react/src/hooks/useEagerConnect.ts, packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json, packages/wallets-list/CHANGELOG.md, packages/wallets-list/package.json, packages/wallets/binance-wallet/CHANGELOG.md, packages/wallets/binance-wallet/package.json, packages/wallets/binance-wallet/src/index.ts, yarn.lock
- [move binance wallet up in wallets display order](https://github.com/lidofinance/reef-knot/commit/a4fe762619f7b413f74c59547f832202a81e97ce)
- [add deeplink, add detector for binance wallet](https://github.com/lidofinance/reef-knot/commit/df2833fa7f7e74527fe34f5048145b7da896126e)
- [remove unsupported chain check from eager connect](https://github.com/lidofinance/reef-knot/pull/161/commits/14a7dfa5f6ca51d4eb732ea1a8314366490b77f3)
=> Follow-up fixes for Binance wallet

.changeset/short-queens-cross.md, packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json, packages/ui-react/CHANGELOG.md, packages/ui-react/package.json, packages/ui-react/src/components/modal/ModalStyles.tsx
=> Fix padding in ModalSubtitleStyle

packages/connect-wallet-modal/CHANGELOG.md, packages/connect-wallet-modal/package.json, packages/connect-wallet-modal/src/connectButtons/ConnectLedger.tsx, packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json
Ledger HID connection metrics fixed
=> fix: ledger hid connect metrics

.changeset/kind-kings-agree.md, apps/demo-react/components/wallet-info/wallet-info-content.tsx, packages/reef-knot/CHANGELOG.md, packages/reef-knot/package.json, packages/wallets-list/CHANGELOG.md, packages/wallets-list/package.json, packages/wallets/ambire/CHANGELOG.md, packages/wallets/ambire/package.json, packages/wallets/ambire/src/index.ts
Added extension support to Ambire connector
=> Support ambire extension

.github/workflows/demo-deploy.yml, .github/workflows/publish-alpha.yml, .github/workflows/publish-dry-run.yml, .github/workflows/publish.yml
Should fix the failed jobs: https://github.com/lidofinance/reef-knot/actions/runs/13495754370
=> Fix workflows: enable corepack before setup-node

.github/workflows/demo-deploy.yml, .github/workflows/publish-alpha.yml, .github/workflows/publish-dry-run.yml, .github/workflows/publish.yml
=> Develop -> Main

apps/demo-react/providers/web3.tsx, packages/connect-wallet-modal/src/components/ReefKnotWalletsModal/getDefaultWalletsModalConfig.ts, packages/connect-wallet-modal/src/connectButtons/ConnectMetaMask.tsx, packages/connect-wallet-modal/src/connectButtons/index.ts, packages/wallets/metamask/src/index.ts
=> MetaMask SDK

packages/connect-wallet-modal/src/connectButtons/ConnectMetaMask.tsx, packages/reef-knot/CHANGELOG.md
- Update reef-knot package changelog for 7.4.0
- Add `walletId` to dependency array in ConnectMetaMask
=> Update changelog, minor fix
