- packages/connect-wallet-modal/CHANGELOG.md
- packages/connect-wallet-modal/package.json
- packages/connect-wallet-modal/src/connectButtons/connectBraveWallet.tsx
- packages/connect-wallet-modal/src/connectButtons/connectCoin98.tsx
- packages/connect-wallet-modal/src/connectButtons/connectGamestop.tsx
- packages/connect-wallet-modal/src/connectButtons/connectMathWallet.tsx
- packages/connect-wallet-modal/src/connectButtons/connectMetamask.tsx
- packages/connect-wallet-modal/src/connectButtons/connectOperaWallet.tsx
- packages/connect-wallet-modal/src/connectButtons/connectTrust.tsx
- packages/connect-wallet-modal/src/connectButtons/connectXdefi.tsx
- packages/connect-wallet-modal/src/constants/conflictChecks.ts
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/web3-react/CHANGELOG.md
- packages/web3-react/package.json
- packages/web3-react/src/hooks/useConnectorTrust.ts
This PR:
- allows users to connect via Trust Wallet browser extension
- handles wallets conflicts related to the Trust Wallet extension
- bumps to v0.1.0
Related:
- https://trustwallet.com/browser-extension
- https://developer.trustwallet.com/trust-wallet-browser-extension/extension-guide
> Trust Wallet browser extension

- packages/connect-wallet-modal/package.json
- packages/reef-knot/.npmignore
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
Fixes:
- `reef-knot` index package v0.1.1 doesn't require latest sub-packages
- `reef-knot` package contains unwanted files in it because there wasn't `.npmignore`
> Fix sub-packages versions in reef-knot's dependencies

- apps/demo-react/util/metrics.ts
- packages/connect-wallet-modal/CHANGELOG.md
- packages/connect-wallet-modal/package.json
- packages/connect-wallet-modal/src/connectButtons/connectAmbire.tsx
- packages/connect-wallet-modal/src/connectButtons/connectBlockchaincom.tsx
- packages/connect-wallet-modal/src/connectButtons/connectBraveWallet.tsx
- packages/connect-wallet-modal/src/connectButtons/connectCoin98.tsx
- packages/connect-wallet-modal/src/connectButtons/connectCoinbase.tsx
- packages/connect-wallet-modal/src/connectButtons/connectExodus.tsx
- packages/connect-wallet-modal/src/connectButtons/connectGamestop.tsx
- packages/connect-wallet-modal/src/connectButtons/connectImToken.tsx
- packages/connect-wallet-modal/src/connectButtons/connectLedger.tsx
- packages/connect-wallet-modal/src/connectButtons/connectMathWallet.tsx
- packages/connect-wallet-modal/src/connectButtons/connectMetamask.tsx
- packages/connect-wallet-modal/src/connectButtons/connectOperaWallet.tsx
- packages/connect-wallet-modal/src/connectButtons/connectTally.tsx
- packages/connect-wallet-modal/src/connectButtons/connectTrust.tsx
- packages/connect-wallet-modal/src/connectButtons/connectWalletConnect.tsx
- packages/connect-wallet-modal/src/connectButtons/connectXdefi.tsx
- packages/connect-wallet-modal/src/connectButtons/connectZenGo.tsx
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
Recently, metrics events for wallets connections were added.
This PR also adds metric events for clicking on wallets connection buttons, since there is a difference between button clicking and actually connecting.
> Add Metrics wallets connection buttons "click" events

- apps/demo-react/components/SettingsWrapper.tsx
- apps/demo-react/components/ThemeSelect.tsx
- apps/demo-react/components/WalletInfo.tsx
- apps/demo-react/package.json
- apps/demo-react/pages/index.tsx
- packages/connect-wallet-modal/CHANGELOG.md
- packages/connect-wallet-modal/package.json
- packages/connect-wallet-modal/src/components/WalletsModal/styles.tsx
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- yarn.lock
Followup for this PR: https://github.com/lidofinance/reef-knot/pull/19
- Fixed the mixed up scrollbar's paddings and margins
- Use colors from theme to support dark color theme
- Add a simple theme select to the demo page
- The 0.5.2 version will also include this change: https://github.com/lidofinance/reef-knot/pull/20
https://user-images.githubusercontent.com/1245209/215496238-0b54f530-ff8e-4e65-a044-75086eca9124.mp4
> Fix: the modal's scrollbar (gutter, dark theme)

- apps/demo-react/components/ProviderWeb3WithProps.tsx
- apps/demo-react/components/WalletInfo.tsx
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/web3-react/CHANGELOG.md
- packages/web3-react/package.json
- packages/web3-react/src/hooks/useSupportedChains.ts
- packages/web3-react/src/hooks/useWeb3.ts
- packages/web3-react/test/hooks/useConnectors.test.tsx
- packages/web3-react/test/hooks/useSupportedChains.test.ts
The main changes are in [useWeb3.ts](https://github.com/lidofinance/reef-knot/compare/shim-wagmi?expand=1#diff-81b322b317f6cfab3801b9a83eab36a6e837bce9451e83d77616f62f1617b3bc) and [useSupportedChains.ts](https://github.com/lidofinance/reef-knot/compare/shim-wagmi?expand=1#diff-09a7cccdcc9ddef855a86be9775530256399960ed3107052cecb16887b6271b1)
A user can connect a wallet either via legacy web3-react connector or via wagmi connector. In the first case, data from wagmi can be undefined. In the second case, data from web3-react can be undefined.
The `useWeb3` hook is used on our staking widget to get data from a wallet, so the shims were added to pass output both from web3-react AND wagmi.
> Shim useWeb3, useSupportedChains

- apps/demo-react/components/ConnectDisconnect.tsx
- apps/demo-react/components/WalletsModal.tsx
- packages/connect-wallet-modal/CHANGELOG.md
- packages/connect-wallet-modal/package.json
- packages/connect-wallet-modal/src/components/WalletsModal/WalletsModal.tsx
- packages/connect-wallet-modal/src/components/WalletsModal/types.ts
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/web3-react/CHANGELOG.md
- packages/web3-react/package.json
- packages/web3-react/src/context/web3.tsx
- packages/web3-react/test/hooks/useConnectors.test.tsx
This PR fixes:
1. Get account address from the shimmed `useWeb3` hook, which works with wagmi, instead of a direct `useWeb3` call from `@web3-react/core`.
2. `providerWeb3` is crucial for transactions, and it wasn't set properly in case of connection via wagmi. I wasn't able to catch this flaw using the demo app, but it became obvious during testing on our widget.
3. A minor cosmetic update for `demo-react` app.
> Fix: account and providerWeb3 via wagmi

- packages/connect-wallet-modal/CHANGELOG.md
- packages/connect-wallet-modal/package.json
- packages/connect-wallet-modal/src/components/WalletsModal/WalletsModal.tsx
- packages/connect-wallet-modal/src/constants/conflictChecks.ts
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/web3-react/CHANGELOG.md
- packages/web3-react/package.json
- packages/web3-react/src/context/web3.tsx
- packages/web3-react/src/hooks/useSupportedChains.ts
- packages/web3-react/src/hooks/useWeb3.ts
- Renames Tally to Taho in conflict checks too
- Reset "I have read and accept Terms of Service" checkbox for all users by updating a localStorage key. The reason is that Lido Terms were significantly updated recently and users should read and accept them one more time. In the future, it should be moved from Reef Knot to a widget level.
- Fix an incorrect setting of providerWeb3 in case of connecting via web3-react. For some reason, Web3Provider class instance can't be used as initial value in `useState()`, but can be set later using `set` function.
- Fix the issues related to choosing an unsupported chain in a wallet, connected via wagmi. The reason of the issues is that wagmi and web3-react have different logic for handling such case. And our widgets historically work with web3-react …
> Fixes for Reef Knot v1 after QA

- .changeset/short-ladybugs-hug.md
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/web3-react/CHANGELOG.md
- packages/web3-react/package.json
- packages/web3-react/src/context/web3.tsx
- packages/web3-react/src/hooks/useWeb3.ts
Fixes ETHUI-415 and UI-620 – the issues with a wrong web3 providers switching when one wallet was disconnected and the other wallet is connected instead.
> Fix(web3-react): web3 providers switch

- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/wallets-helpers/CHANGELOG.md
- packages/wallets-helpers/package.json
- packages/wallets-helpers/src/factories/walletConnectConnector.ts
The flag is needed for testing purposes of WalletConnect v2.
To enable WC v2 QR modal, run this in the dev console and restart the page:
```
window.localStorage.setItem('reefknot_wcv2_enable', 'true')
```
Also moves the date of autoswitching to WC v2 to 24.06 from 20.06
> Add 'reefknot_wcv2_enable' localstorage flag

- packages/connect-wallet-modal/CHANGELOG.md
- packages/connect-wallet-modal/package.json
- packages/connect-wallet-modal/src/connectButtons/ConnectWC.tsx
- packages/core-react/CHANGELOG.md
- packages/core-react/package.json
- packages/core-react/src/context/index.tsx
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/ui-react/CHANGELOG.md
- packages/ui-react/package.json
- packages/ui-react/src/components/WCWarnBanner/GradientBanner.styles.tsx
- packages/ui-react/src/components/WCWarnBanner/GradientBanner.tsx
- packages/ui-react/src/components/WCWarnBanner/WCWarnBanner.tsx
- packages/ui-react/src/components/WCWarnBanner/WCWarnBannerAutoRequest.tsx
- packages/ui-react/src/components/WCWarnBanner/WCWarnBannerContext.tsx
- packages/ui-react/src/components/WCWarnBanner/WCWarnBannerContextProvider.tsx
- packages/ui-react/src/components/WCWarnBanner/WCWarnBannerRequest.tsx
- packages/ui-react/src/components/WCWarnBanner/index.ts
- packages/ui-react/src/components/index.ts
- turbo.json
- yarn.lock
> feature: permanent "walletconnect has issues" notification for WCv2"

- package.json
- packages/connect-wallet-modal/CHANGELOG.md
- packages/connect-wallet-modal/package.json
- packages/connectors/ledger-connector/.eslintrc.json
- packages/connectors/ledger-connector/CHANGELOG.md
- packages/connectors/ledger-connector/package.json
- packages/connectors/ledger-connector/rollup.config.js
- packages/connectors/ledger-connector/src/README.md
- packages/connectors/ledger-connector/src/hid/connector.ts
- packages/connectors/ledger-connector/src/hid/helpers.ts
- packages/connectors/ledger-connector/src/hid/index.ts
- packages/connectors/ledger-connector/src/hid/provider.ts
- packages/connectors/ledger-connector/src/hid/signer.ts
- packages/connectors/ledger-connector/src/hid/types.ts
- packages/connectors/ledger-connector/src/iframe/connector.ts
- packages/connectors/ledger-connector/src/iframe/helpers.ts
- packages/connectors/ledger-connector/src/iframe/index.ts
- packages/connectors/ledger-connector/src/index.ts
- packages/connectors/ledger-connector/tsconfig.json
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/web3-react/CHANGELOG.md
- packages/web3-react/README.md
- packages/web3-react/package.json
- packages/web3-react/src/context/connectors.tsx
- packages/web3-react/src/hooks/useConnectorInfo.ts
- packages/web3-react/src/hooks/useConnectorLedger.ts
- packages/web3-react/test/hooks/useConnectorInfo.test.ts
- yarn.lock
1. The code is moved to Reef Knot from (closes UI-89):
- https://github.com/lidofinance/ledgerhq-frame-connector
- https://github.com/lidofinance/ledgerhq-connector
The connectors are now stored in single `@reef-knot/ledger-connector` package
2. Pass supportedChainIds to LedgerHQFrameConnector following this:
https://github.com/lidofinance/ledgerhq-frame-connector/pull/11
> Move ledgerhq libraries into reef-knot

- packages/connectors/ledger-connector/CHANGELOG.md
- packages/connectors/ledger-connector/package.json
- packages/connectors/ledger-connector/src/hid/signer.ts
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
Fixes the issue: `TypeError: _ledgerhq_hw_app_eth_lib_services_ledger__WEBPACK_IMPORTED_MODULE_2__.resolveTransaction is not a function`
The issue could happen in runtime in a project, which uses the `reef-knot` package.
The reason of the issue: ledgerService wasn't imported properly, named import fixes it.
> Fix: ledgerService import

- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/wallets-helpers/CHANGELOG.md
- packages/wallets-helpers/package.json
- packages/wallets-helpers/src/walletconnect/getWalletConnectConnector.ts
Throwing an error in this case can break a build for a project which doesn't provide the ID on the build step.
> Fix: warn instead of throw when WC project id is empty

- packages/eslint-config-custom/index.js
`yarn lint` produces no new linting errors or warnings.
Closes UI-877
> Clean up eslint config

- packages/connect-wallet-modal/CHANGELOG.md
- packages/connect-wallet-modal/package.json
- packages/connect-wallet-modal/src/components/WalletsModal/WalletsModal.tsx
- packages/core-react/CHANGELOG.md
- packages/core-react/package.json
- packages/core-react/src/constants/index.ts
- packages/core-react/src/constants/localStorage.ts
- packages/core-react/src/context/index.ts
- packages/core-react/src/index.ts
- packages/eslint-config-custom/index.js
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/web3-react/CHANGELOG.md
- packages/web3-react/package.json
- packages/web3-react/src/hooks/useAutoConnect.ts
- yarn.lock
Related to #72
Call this Terms acceptance modal less frequently by checking if the Terms were accepted earlier.
Also:
- updates yarn.lock after #79 
- fix eslint import/resolver which appears to be broken after #75
> Fix: open Terms modal only if terms were not accepted earlier

- packages/connect-wallet-modal/CHANGELOG.md
- packages/connect-wallet-modal/package.json
- packages/connect-wallet-modal/src/components/WalletsModal/WalletsModal.tsx
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/web3-react/CHANGELOG.md
- packages/web3-react/package.json
- packages/web3-react/src/hooks/useAutoConnect.ts
**Related:** #80 
The issue was found during QA session: if a user rejects the connection via wallet's UI, then the Terms modal window still closes. So the wallet is not connected and it becomes possible to open the common Wallet Connection Modal with a list of all wallets, which is not expected behavior.
This PR fixes the issue.
> Fix: connection rejection logic during mobile browser autoconnect

- .github/workflows/check.yml
Not sure that I did everything right.
The intention is to disable automatic deployments and run the workflow manually.
Now, the deployed branch can be unintentionally replaced by another branch. It is not convenient, for example if a QA is testing a specific branch and a developer opened another PR at the same moment, which triggers unwanted redeploy.
> Update demo app deploy workflow: run manually

- packages/connect-wallet-modal/rollup.config.js
- packages/connectors/ledger-connector/rollup.config.js
- packages/core-react/rollup.config.js
- packages/reef-knot/rollup.config.js
- packages/ui-react/rollup.config.js
- packages/wallets-helpers/rollup.config.js
- packages/wallets-icons/rollup.config.js
- packages/wallets-list/rollup.config.js
- packages/wallets/ambire/rollup.config.js
- packages/wallets/bitkeep/rollup.config.js
- packages/wallets/coin98/rollup.config.js
- packages/wallets/exodus/rollup.config.js
- packages/wallets/okx/rollup.config.js
- packages/wallets/phantom/rollup.config.js
- packages/wallets/taho/rollup.config.js
- packages/wallets/walletconnect/rollup.config.js
- packages/wallets/zengo/rollup.config.js
- packages/wallets/zerion/rollup.config.js
- packages/web3-react/rollup.config.js
Disable ts diagnostic checks to speed up compilation during development and get rid of annoying issues with types rebuilding during development.
See https://www.npmjs.com/package/rollup-plugin-typescript2#plugin-options
> check: true
> Set to false to avoid doing any diagnostic checks on the code. Setting to false is sometimes referred to as transpileOnly by other TypeScript integrations.
> Set `check: false` for rollup-plugin-typescript2 config

- packages/connectors/ledger-connector/CHANGELOG.md
- packages/connectors/ledger-connector/package.json
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- yarn.lock
Needed to bump `crypto-js` to 4.2.0 to fix dependabot security alert:  
https://github.com/lidofinance/reef-knot/security/dependabot/36
> Update ledgerhq/hw-app-eth (crypto-js alert)

- apps/demo-react/components/ProviderWeb3WithProps.tsx
- packages/connect-wallet-modal/CHANGELOG.md
- packages/connect-wallet-modal/package.json
- packages/connect-wallet-modal/src/components/Ledger/LedgerDerivationPathSelect.tsx
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/web3-react/CHANGELOG.md
- packages/web3-react/package.json
- packages/web3-react/src/hooks/useConnectorLedger.ts
The main reason of the PR is to add a workaround for an issue when connection does not happen because of `Warning: Suppressed stale connector activation [object Object]`
Also this PR:
- (demo-react) makes demo-react app work with holesky by default
- (connect-wallet-modal) removes deprecated prop from Select
> Fix: ledger connection await timeout

- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/web3-react/CHANGELOG.md
- packages/web3-react/package.json
- packages/web3-react/src/hooks/useAutoConnect.ts
Fixes an issue with the Terms modal not closing after successful connect until page restart.
> Fix: Terms modal not closing during autoconnect

- packages/connect-wallet-modal/CHANGELOG.md
- packages/connect-wallet-modal/package.json
- packages/connect-wallet-modal/src/components/WalletsModalForEth/WalletsModalForEth.tsx
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/wallets-list/CHANGELOG.md
- packages/wallets-list/package.json
- packages/wallets/bitkeep/CHANGELOG.md
- packages/wallets/bitkeep/package.json
- packages/wallets/bitkeep/src/index.ts
- packages/wallets/brave/CHANGELOG.md
- packages/wallets/brave/package.json
- packages/wallets/brave/src/index.ts
- packages/wallets/coin98/package.json
- packages/wallets/coin98/src/index.ts
- packages/wallets/exodus/CHANGELOG.md
- packages/wallets/exodus/package.json
- packages/wallets/exodus/src/index.ts
- packages/wallets/okx/CHANGELOG.md
- packages/wallets/okx/package.json
- packages/wallets/okx/src/index.ts
Resolves SI-954
We have several Wallet Adapters. Each Wallet Adapter uses its own instance of InjectedConnector.
1. Autoconnect by wagmi checks last used connector first: [here](https://github.com/wagmi-dev/wagmi/blob/fcdbe3531e6d05cda4a4a511bae1ad4c9e426d88/packages/core/src/client.ts#L229)
2. Last used connector is stored in localstorage [like this](https://github.com/wagmi-dev/wagmi/blob/fcdbe3531e6d05cda4a4a511bae1ad4c9e426d88/packages/core/src/client.ts#L296) and is being set [here](https://github.com/wagmi-dev/wagmi/blob/88afc84978afe9689ab7364633e4422ecd7699ea/packages/core/src/actions/accounts/connect.ts#L39) using connector's id
3. The problem is that all InjectedConnectors have the `id === 'injected'` property: [see here](https://github.com/wagmi-dev/references/blob/6c841d4d6d264 …
> Fix: wrong connector after page reload

- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/wallets-list/CHANGELOG.md
- packages/wallets-list/package.json
- packages/wallets-list/src/ethereum.ts
- packages/wallets/browserExtension/package.json
- turbo/generators/wallet/templates/package.json.hbs
Fixes this issue during publishing to NPM:
> error an error occurred while publishing @reef-knot/wallet-adapter-browserExtension: E400 400 Bad Request - PUT https://registry.npmjs.org/@reef-knot%2fwallet-adapter-browserExtension - "@reef-knot/wallet-adapter-browserExtension" is invalid for new packages
> Fix name of the "wallet-adapter-browser-extension" package

- apps/demo-react/components/ConnectDisconnect.tsx
- packages/core-react/CHANGELOG.md
- packages/core-react/package.json
- packages/core-react/src/hooks/index.ts
- packages/core-react/src/hooks/useAutoConnectCheck.ts
- packages/core-react/src/hooks/useConnectorInfo.ts
- packages/core-react/src/hooks/useDisconnect.ts
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
Current `isAutoConnectionSuitable` is working only for connected wallets by mistake.
This PR fixes it and moves this check to a separate `useAutoConnectCheck` hook.
> Fix: isAutoConnectionSuitable

- .github/workflows/check.yml
- .github/workflows/release.yml
From https://github.com/lidofinance/reef-knot/actions/runs/8138636662:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
The PR updates GitHub actions.
It seems that the updated actions work okay: https://github.com/lidofinance/reef-knot/actions/runs/8378819666/job/22944300107
> Update GitHub actions for Node v20

- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
- packages/ui-react/package.json
- packages/wallets-helpers/package.json
- yarn.lock
This is an attempt to fix the issue when yarn v3 doesn't correctly install peer deps from the sub-packages of reef-knot (see https://github.com/lidofinance/lido-ethereum-sdk/pull/145)
> Add peer deps to root package

- apps/demo-react/components/ConfigContextProviders.tsx
- packages/core-react/src/context/reefKnot.tsx
1. Rename ReefKnot to ReefKnotProvider
2. Change props – get only one config prop
`<ReefKnotProvider config={reefKnotConfig}>`
> refactor: reef knot provider naming improved and config prop defined

- apps/demo-react/components/ConfigContextProviders.tsx
- apps/demo-react/components/ProviderSDKWithProps.tsx
- apps/demo-react/components/WalletsModal.tsx
- packages/connect-wallet-modal/README.md
- packages/connect-wallet-modal/src/components/EagerConnectModal/EagerConnectModal.tsx
- packages/core-react/src/context/reefKnot.tsx
Removing rpc, chains props from ReefKnot provider because they are not used at all, so there is no need to configure and to store them.
> refactor: removing reefknot config args rpc and chains because of no use

- packages/connectors/ledger-connector/CHANGELOG.md
- packages/connectors/ledger-connector/package.json
- packages/connectors/ledger-connector/src/iframe/connector.ts
- packages/connectors/ledger-connector/src/iframe/provider.ts
- packages/reef-knot/CHANGELOG.md
- packages/reef-knot/package.json
Fix: wrap `IFrameEthereumProvider` in `LedgerIFrameProvider` with the `request` method, which is required for `useWalletClient` wagmi hook
> Fix: Ledger Live Provider – add "request" method

- packages/wallets/safe/src/index.ts
Disable eslint warning because it is breaking a release
> Fix: disable eslint warning

- turbo.json
"tui" allows for viewing each log at once and interacting with the task. "stream" outputs logs as they come in and is not interactive.
Setting the option to "tui" because it is more convenient than the default option after updating turbo to v2.
> Use "tui" in turbo.json

- README.md
- docs/migration-guide.md
The PR updates the docs by adding:
- reef-knot installation instructions in the project's README
- migration guide from reef-knot 0.x to the current latest version
This changes doesn't require a new release or testing.
> Add migration guide for the latest reef knot version

- .github/workflows/test.yml
- playwright-tests/pages/components/index.ts
- playwright-tests/pages/components/stats.ts
- playwright-tests/pages/components/wrap-unwrap-block.ts
- playwright-tests/pages/reefKnot.page.ts
- playwright-tests/playwright.config.ts
- playwright-tests/services/helpers.ts
- playwright-tests/services/sdk.service.ts
- playwright-tests/test-data/matomo.data.ts
- playwright-tests/tests/transactions/stake-tx.spec.ts
- playwright-tests/tests/transactions/unwrap-tx.spec.ts
- playwright-tests/tests/transactions/wrap-tx.spec.ts
- playwright-tests/tests/wallet-stats.spec.ts
- added tests for
- Wrap ETH
- Wrap stETH
- Unwrap wstETH
- changed XDEFI wallet to Ctrl wallet
- some fixes
- [Test ReefKnot action](https://github.com/lidofinance/reef-knot/actions/runs/13033160318)
> Tests for wrap/unwrap transactions

- .github/workflows/demo-deploy.yml
- .github/workflows/publish-alpha.yml
- .github/workflows/publish-dry-run.yml
- .github/workflows/publish.yml
Without this fix, the workflows are trying to use yarn v1, but we need v4.
> Set yarn version during workflows

- apps/demo-react/utils/metrics.ts
- packages/connect-wallet-modal/src/components/Ledger/LedgerAccountScreen.tsx
- packages/connect-wallet-modal/src/components/Ledger/LedgerContext.tsx
- packages/core-react/src/context/reefKnotContext.ts
- packages/core-react/src/helpers/getDefaultConfig.ts
- packages/core-react/src/helpers/withCallback.ts
- packages/core-react/src/helpers/wrapWithCallback.ts
- packages/core-react/src/hooks/useAutoConnect.ts
- packages/core-react/src/hooks/useEagerConnect.ts
- packages/types/src/index.ts
- packages/types/src/reef-knot-config.ts
- tsconfig.json
Adds ability to pass onAutoConnect and onReconnect callbacks to the reef-knot config.
* [`packages/core-react/src/hooks/useAutoConnect.ts`](diffhunk://#diff-b64608f5936b81a1b3b9592acaaf302e80a735c8b2c94c5e0d86c02f3e21e1eaR7-R14): Imported `wrapWithCallback` and used it to wrap `reconnectAsync` with `onReconnect` callback if provided.
* [`packages/core-react/src/hooks/useEagerConnect.ts`](diffhunk://#diff-257e1cadcb8217d37d240b832fe2da4b2d4e2144aa007d4b32ff30f29ec7a352L68-R85): Updated `eagerConnect` to call `onAutoConnect` callback if provided after a successful connection.
* [`packages/core-react/src/helpers/wrapWithCallback.ts`](diffhunk://#diff-91e4f36c0a052bb22f09e814a24b7ca30f3e8fd359ca73e9bc3596733b2dce98R1-R14): Added a utility function `wrapWithCallback` to wrap a function and …
> Add onAutoConnect, onReconnect

- packages/connectors/ledger-connector/package.json
- packages/types/package.json
- packages/wallets/ambire/package.json
- packages/wallets/binance-wallet/package.json
- packages/wallets/bitkeep/package.json
- packages/wallets/brave/package.json
- packages/wallets/browserExtension/package.json
- packages/wallets/coin98/package.json
- packages/wallets/coinbase-smart-wallet/package.json
- packages/wallets/coinbase/package.json
- packages/wallets/ctrl/package.json
- packages/wallets/dappBrowserInjected/package.json
- packages/wallets/exodus/package.json
- packages/wallets/imtoken/package.json
- packages/wallets/ledger-hid/package.json
- packages/wallets/ledger-live/package.json
- packages/wallets/metamask/package.json
- packages/wallets/okx/package.json
- packages/wallets/phantom/package.json
- packages/wallets/safe/package.json
- packages/wallets/trust/package.json
- packages/wallets/walletconnect/package.json
- packages/wallets/xdefi/package.json
- turbo/generators/wallet/templates/package.json.hbs
The PR should fix this error during npm publish with provenance:
> 'npm ERR! 422 Unprocessable Entity - PUT https://registry.npmjs.org/@reef-knot%2fledger-connector - Error verifying sigstore provenance bundle: Failed to validate repository information: package.json: "repository.url" is "", expected to match "https://github.com/lidofinance/reef-knot" from provenance\n'
> Fix: add missing repository fields for packages to fix provenance

- packages/wallets/safe/src/index.ts
Holesky Safe is going to sunset and, as part of migration to Hoodi, it is required to change allowed domain for safe connector.
> Update allowed domain for safe connector
